package com.intelligentrecruitment.interview.application;

import com.intelligentrecruitment.shared.error.ApiException;
import com.intelligentrecruitment.tenancy.application.WorkspaceAccessService;
import org.springframework.http.HttpStatus;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import java.time.Instant;
import java.util.*;
import static com.intelligentrecruitment.shared.database.SqlTimes.timestamp;

@Service
public class InterviewService {
    private final JdbcTemplate jdbc; private final WorkspaceAccessService access;
    public InterviewService(JdbcTemplate jdbc, WorkspaceAccessService access){this.jdbc=jdbc;this.access=access;}
    public List<KitSummary> list(UUID userId, UUID workspaceId){access.requireBusinessAccess(userId,workspaceId);return jdbc.query("SELECT k.id,k.candidate_id,c.display_name_masked,k.status,k.created_at FROM interview_kits k JOIN candidates c ON c.id=k.candidate_id WHERE k.workspace_id=? ORDER BY k.created_at DESC",(r,n)->new KitSummary(r.getObject("id",UUID.class),r.getObject("candidate_id",UUID.class),r.getString("display_name_masked"),r.getString("status"),r.getTimestamp("created_at").toInstant()),workspaceId);}
    @Transactional public KitDetail create(UUID userId, UUID workspaceId, CreateInput input){access.requireBusinessAccess(userId,workspaceId);if(input.candidateId()==null)throw new ApiException("CANDIDATE_REQUIRED","请选择候选人",HttpStatus.BAD_REQUEST);Boolean exists=jdbc.queryForObject("SELECT EXISTS(SELECT 1 FROM candidates WHERE id=? AND workspace_id=?)",Boolean.class,input.candidateId(),workspaceId);if(!Boolean.TRUE.equals(exists))throw new ApiException("CANDIDATE_NOT_FOUND","候选人不存在",HttpStatus.NOT_FOUND);Instant now=Instant.now();UUID kit=UUID.randomUUID(),ver=UUID.randomUUID();UUID company=jdbc.queryForObject("SELECT company_id FROM workspaces WHERE id=?",UUID.class,workspaceId);jdbc.update("INSERT INTO interview_kits(id,company_id,workspace_id,job_version_id,candidate_id,screening_result_id,status,created_by,created_at,updated_at) VALUES(?,?,?,?,?,?,'DRAFT',?,?,?)",kit,company,workspaceId,input.jobVersionId(),input.candidateId(),input.screeningResultId(),userId,timestamp(now),timestamp(now));jdbc.update("INSERT INTO interview_kit_versions(id,company_id,workspace_id,kit_id,screening_result_id,version_no,status,created_by,created_at) VALUES(?,?,?,?,?,1,'DRAFT',?,?)",ver,company,workspaceId,kit,input.screeningResultId(),userId,timestamp(now));List<Question> qs=generate(ver,company,workspaceId,input.questionCount());return detail(kit,qs);}
    @Transactional public KitDetail update(UUID userId,UUID workspaceId,UUID kitId,List<QuestionInput> questions){access.requireBusinessAccess(userId,workspaceId);UUID ver=jdbc.queryForObject("SELECT id FROM interview_kit_versions WHERE kit_id=? AND workspace_id=? ORDER BY version_no DESC LIMIT 1",UUID.class,kitId,workspaceId);jdbc.update("DELETE FROM interview_questions WHERE kit_version_id=?",ver);UUID company=jdbc.queryForObject("SELECT company_id FROM workspaces WHERE id=?",UUID.class,workspaceId);int i=0;for(QuestionInput q:questions)jdbc.update("INSERT INTO interview_questions(id,company_id,workspace_id,kit_version_id,category,content,rationale,focus_points,scoring_points,evidence_refs,sort_order) VALUES(?,?,?,?,?,?,?,?,?,?,?)",UUID.randomUUID(),company,workspaceId,ver,q.category(),q.content(),q.rationale(),q.focusPoints(),q.scoringPoints(),q.evidenceRefs(),i++);return detail(kitId,questions.stream().map(q->new Question(null,q.category(),q.content(),q.rationale(),q.focusPoints(),q.scoringPoints(),q.evidenceRefs(),0)).toList());}
    @Transactional public KitDetail confirm(UUID userId,UUID workspaceId,UUID kitId){access.requireBusinessAccess(userId,workspaceId);jdbc.update("UPDATE interview_kits SET status='CONFIRMED',updated_at=? WHERE id=? AND workspace_id=?",timestamp(Instant.now()),kitId,workspaceId);jdbc.update("UPDATE interview_kit_versions SET status='CONFIRMED' WHERE kit_id=?",kitId);return get(userId,workspaceId,kitId);}
    public KitDetail get(UUID userId,UUID workspaceId,UUID kitId){access.requireBusinessAccess(userId,workspaceId);List<Question> q=jdbc.query("SELECT iq.id,iq.category,iq.content,iq.rationale,iq.focus_points,iq.scoring_points,iq.evidence_refs,iq.sort_order FROM interview_questions iq JOIN interview_kit_versions v ON v.id=iq.kit_version_id WHERE v.kit_id=? ORDER BY iq.sort_order",(r,n)->new Question(r.getObject("id",UUID.class),r.getString("category"),r.getString("content"),r.getString("rationale"),r.getString("focus_points"),r.getString("scoring_points"),r.getString("evidence_refs"),r.getInt("sort_order")),kitId);return detail(kitId,q);}
    private List<Question> generate(UUID ver,UUID company,UUID workspace,int count){List<Question> out=new ArrayList<>();String[] cats={"专业","行为","场景","追问"};for(int i=0;i<Math.max(4,Math.min(count,20));i++){String cat=cats[i%cats.length],content="请结合你的实际经历，说明一个与岗位相关的"+cat+"案例，并阐述你的判断、行动和结果。";Question q=new Question(UUID.randomUUID(),cat,content,"验证候选人的岗位匹配与问题解决能力","背景、决策、结果、复盘","清晰度、真实性、结果可验证性","候选人简历/筛选结果",i);out.add(q);jdbc.update("INSERT INTO interview_questions(id,company_id,workspace_id,kit_version_id,category,content,rationale,focus_points,scoring_points,evidence_refs,sort_order) VALUES(?,?,?,?,?,?,?,?,?,?,?)",q.id(),company,workspace,ver,q.category(),q.content(),q.rationale(),q.focusPoints(),q.scoringPoints(),q.evidenceRefs(),i);}return out;}
    private KitDetail detail(UUID id,List<? extends Question> q){return new KitDetail(id,q);}
    public record CreateInput(UUID candidateId,UUID jobVersionId,UUID screeningResultId,int questionCount){}
    public record QuestionInput(String category,String content,String rationale,String focusPoints,String scoringPoints,String evidenceRefs){}
    public record Question(UUID id,String category,String content,String rationale,String focusPoints,String scoringPoints,String evidenceRefs,int sortOrder){}
    public record KitSummary(UUID id,UUID candidateId,String candidateName,String status,Instant createdAt){}
    public record KitDetail(UUID id,List<? extends Question> questions){}
}
