package com.intelligentrecruitment.billing.api;

import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.intelligentrecruitment.boss.application.BossControlPlaneClient;
import com.intelligentrecruitment.shared.security.CurrentUser;
import jakarta.validation.Valid;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.Positive;
import java.util.Map;
import java.util.UUID;
import org.springframework.security.core.Authentication;
import org.springframework.http.MediaType;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestPart;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;
import org.springframework.web.multipart.MultipartFile;

/** Read-only BFF for BOSS-owned wallet and statement data. Payment operations are not local. */
@RestController
@RequestMapping("/api/v1/companies/{companyId}/billing")
public class BossBillingController {
    private final BossControlPlaneClient boss;
    private final ObjectMapper json;
    public BossBillingController(BossControlPlaneClient boss, ObjectMapper json) { this.boss = boss; this.json = json; }

    @GetMapping
    Map<String, Object> billing(@PathVariable UUID companyId, Authentication authentication) {
        String token = CurrentUser.bossAccessToken(authentication);
        JsonNode wallet = boss.companyWallet(token, companyId);
        JsonNode statements = boss.companyStatements(token, companyId);
        Map<String, Object> result = json.convertValue(wallet, new com.fasterxml.jackson.core.type.TypeReference<Map<String, Object>>() { });
        result.put("statements", json.convertValue(statements, new com.fasterxml.jackson.core.type.TypeReference<Object>() { }));
        return result;
    }

    /** BOSS is the source of truth for available payment channels and receiving accounts. */
    @GetMapping("/recharge-context")
    JsonNode rechargeContext(@PathVariable UUID companyId, Authentication authentication) {
        return boss.paymentContext(CurrentUser.bossAccessToken(authentication), companyId);
    }

    /** Returns the signed Alipay form generated by BOSS; this service never signs or stores payment secrets. */
    @PostMapping("/recharge/alipay")
    JsonNode createAlipayOrder(@PathVariable UUID companyId, @Valid @RequestBody CreateRechargeOrder request,
                               Authentication authentication) {
        return boss.createAlipayPayment(CurrentUser.bossAccessToken(authentication), companyId,
                request.amountMinor(), request.payerName());
    }

    @PostMapping("/recharge/transfer")
    JsonNode createTransferOrder(@PathVariable UUID companyId, @Valid @RequestBody CreateRechargeOrder request,
                                 Authentication authentication) {
        return boss.createTransferPayment(CurrentUser.bossAccessToken(authentication), companyId,
                request.amountMinor(), request.payerName());
    }

    @PostMapping(value = "/recharge/transfer/{orderId}/proof", consumes = MediaType.MULTIPART_FORM_DATA_VALUE)
    void uploadTransferProof(@PathVariable UUID companyId, @PathVariable UUID orderId, @RequestPart("file") MultipartFile file,
                             Authentication authentication) {
        boss.uploadTransferProof(CurrentUser.bossAccessToken(authentication), companyId, orderId, file);
    }

    public record CreateRechargeOrder(@Positive long amountMinor, @NotBlank String payerName) { }
}
