ALTER TABLE enterprise_talent_pool_copies ADD COLUMN IF NOT EXISTS sync_status VARCHAR(24) NOT NULL DEFAULT 'SYNCED' CHECK (sync_status IN ('SYNCED','PENDING_UPDATE','SYNC_FAILED'));
ALTER TABLE enterprise_job_pool_copies ADD COLUMN IF NOT EXISTS sync_status VARCHAR(24) NOT NULL DEFAULT 'SYNCED' CHECK (sync_status IN ('SYNCED','PENDING_UPDATE','SYNC_FAILED'));
