"use client";

import { Building2, EyeOff, LogOut, MailPlus, Plus, UserRound, UsersRound } from "lucide-react";
import { FormEvent, useEffect, useState } from "react";
import { AppShell } from "@/components/layout/app-shell";
import { apiFetch, ApiError } from "@/lib/api-client";

type Me={id:string;maskedPhone:string;personalVerificationStatus:string};
type Company={id:string;displayName:string;legalName:string;verificationStatus:string;role:string};
type Workspace={id:string;companyId:string|null;type:string;name:string;ownerUserId:string;status:string;memberCount:number;hasDataAccess:boolean;currentRole:string|null};

export default function SettingsPage(){
  const [me,setMe]=useState<Me|null>(null);const[companies,setCompanies]=useState<Company[]>([]);const[workspaces,setWorkspaces]=useState<Workspace[]>([]);const[message,setMessage]=useState("");
  async function load(){try{const[u,c,w]=await Promise.all([apiFetch<Me>("/me"),apiFetch<Company[]>("/companies"),apiFetch<Workspace[]>("/workspaces")]);setMe(u);setCompanies(c);setWorkspaces(w);}catch(e){setMessage(e instanceof ApiError?e.message:"加载失败");}}
  useEffect(()=>{let active=true;Promise.all([apiFetch<Me>("/me"),apiFetch<Company[]>("/companies"),apiFetch<Workspace[]>("/workspaces")]).then(([u,c,w])=>{if(active){setMe(u);setCompanies(c);setWorkspaces(w);}}).catch(e=>{if(active)setMessage(e instanceof ApiError?e.message:"加载失败");});return()=>{active=false};},[]);
  return <AppShell activeItem="设置"><section><h1 className="m-0 text-[25px] font-bold text-[#09245d]">组织与工作空间</h1><p className="mt-1 text-sm text-[#55709d]">企业角色只管理治理元数据，招聘数据始终按 Workspace 成员关系隔离。</p></section>
    {message&&<p className="mt-4 rounded-lg bg-red-50 p-3 text-sm text-red-700">{message}</p>}
    <div className="mt-5 grid gap-4 xl:grid-cols-[340px_minmax(0,1fr)]"><aside className="space-y-4"><Card><UserRound className="text-[#2f6bff]"/><h2 className="mb-1 mt-3 text-base">当前账号</h2><p className="m-0 text-sm text-[#667d9f]">{me?.maskedPhone??"加载中…"}</p><span className="mt-3 inline-block rounded-md bg-[#edf5ff] px-2 py-1 text-xs text-[#2467ca]">实名认证：{me?.personalVerificationStatus??"--"}</span>{me?.personalVerificationStatus==="UNVERIFIED"&&<PersonalVerify onDone={load}/>}<button type="button" onClick={async()=>{await apiFetch("/auth/logout-all",{method:"POST"});window.location.replace("/login");}} className="outline-button mt-4 w-full text-red-600"><LogOut size={15}/>退出全部设备</button></Card>
      <Card><Building2 className="text-[#16a477]"/><h2 className="mb-3 mt-3 text-base">所属企业</h2>{companies.length?companies.map(c=><div key={c.id} className="mb-2 rounded-lg border border-[#dce7f3] p-3"><strong className="text-sm">{c.displayName}</strong><small className="mt-1 block text-[#7187a8]">{c.role} · {c.verificationStatus}</small></div>):<p className="text-sm text-[#7187a8]">尚未加入企业</p>}</Card></aside>
      <section><div className="grid gap-3 md:grid-cols-2">{workspaces.map(w=><Card key={w.id}><div className="flex items-start justify-between"><span className="grid h-10 w-10 place-items-center rounded-xl bg-[#eaf7ff] text-[#2471dc]"><UsersRound size={20}/></span><span className={`rounded-md px-2 py-1 text-xs ${w.hasDataAccess?"bg-emerald-50 text-emerald-700":"bg-slate-100 text-slate-600"}`}>{w.hasDataAccess?"可访问业务数据":"仅治理元数据"}</span></div><h2 className="mb-1 mt-3 text-base">{w.name}</h2><p className="m-0 text-xs text-[#7187a8]">{w.type} · {w.memberCount} 名成员 · {w.status}</p>{!w.hasDataAccess&&<p className="mt-3 flex items-center gap-2 text-xs text-[#667d9f]"><EyeOff size={14}/>未加入该 Workspace，职位、人才、简历和任务不可见</p>}</Card>)}</div>
      {me&&companies.some(c=>["COMPANY_OWNER","COMPANY_ADMIN"].includes(c.role))&&<CreateWorkspace companies={companies} ownerId={me.id} onDone={load}/>}<TeamInvitations key={`${companies.length}:${workspaces.length}`} companies={companies} workspaces={workspaces}/></section></div>
  </AppShell>;
}

function CreateWorkspace({companies,ownerId,onDone}:{companies:Company[];ownerId:string;onDone:()=>Promise<void>}){const[companyId,setCompanyId]=useState(companies[0]?.id??"");const[name,setName]=useState("");const[msg,setMsg]=useState("");async function submit(e:FormEvent){e.preventDefault();try{await apiFetch(`/companies/${companyId}/workspaces`,{method:"POST",body:JSON.stringify({name,ownerUserId:ownerId})});setName("");setMsg("Workspace 已创建，你被指定为 Workspace Owner。");await onDone();}catch(err){setMsg(err instanceof ApiError?err.message:"创建失败");}}return <form onSubmit={submit} className="mt-4 rounded-xl border border-[#d6e5f5] bg-white p-5"><h2 className="m-0 flex items-center gap-2 text-base"><Plus size={17}/>创建企业 Workspace</h2><p className="mt-1 text-xs text-[#7187a8]">仅 Company Owner/Admin 可创建；创建者只有成为空间成员后才拥有业务数据权限。</p><div className="mt-4 grid gap-3 sm:grid-cols-[220px_1fr_auto]"><select value={companyId} onChange={e=>setCompanyId(e.target.value)} className="h-10 rounded-lg border border-[#cbdbea] px-3 text-sm">{companies.filter(c=>["COMPANY_OWNER","COMPANY_ADMIN"].includes(c.role)).map(c=><option key={c.id} value={c.id}>{c.displayName}</option>)}</select><input required value={name} onChange={e=>setName(e.target.value)} placeholder="Workspace 名称" className="h-10 rounded-lg border border-[#cbdbea] px-3 text-sm"/><button className="primary-button !h-10" type="submit">创建</button></div>{msg&&<p className="mb-0 mt-3 text-sm text-[#526f98]">{msg}</p>}</form>}
function PersonalVerify({onDone}:{onDone:()=>Promise<void>}){const[name,setName]=useState("");const[number,setNumber]=useState("");const[msg,setMsg]=useState("");async function submit(e:FormEvent){e.preventDefault();try{await apiFetch("/personal-verifications",{method:"POST",body:JSON.stringify({realName:name,identityNumber:number})});setMsg("认证已提交，平台审核通过后发放30元试用金。");await onDone();}catch(err){setMsg(err instanceof ApiError?err.message:"提交失败");}}return <form onSubmit={submit} className="mt-4 space-y-2 border-t border-[#e0eaf5] pt-4"><input required value={name} onChange={e=>setName(e.target.value)} placeholder="真实姓名" className="h-9 w-full rounded-lg border border-[#cbdbea] px-3 text-sm"/><input required value={number} onChange={e=>setNumber(e.target.value)} placeholder="身份证明号码" className="h-9 w-full rounded-lg border border-[#cbdbea] px-3 text-sm"/><button className="outline-button !h-9 w-full" type="submit">提交实名认证</button>{msg&&<p className="text-xs text-[#526f98]">{msg}</p>}</form>}
function TeamInvitations({companies,workspaces}:{companies:Company[];workspaces:Workspace[]}){const companyOptions=companies.filter(c=>["COMPANY_OWNER","COMPANY_ADMIN"].includes(c.role));const workspaceOptions=workspaces.filter(w=>["WORKSPACE_OWNER","WORKSPACE_ADMIN"].includes(w.currentRole??""));const[scope,setScope]=useState(workspaceOptions.length?"workspace":"company");const[target,setTarget]=useState(workspaceOptions[0]?.id??companyOptions[0]?.id??"");const[phone,setPhone]=useState("");const[role,setRole]=useState(workspaceOptions.length?"RECRUITER":"COMPANY_MEMBER");const[msg,setMsg]=useState("");if(!companyOptions.length&&!workspaceOptions.length)return null;async function submit(e:FormEvent){e.preventDefault();try{const path=scope==="company"?`/companies/${target}/invitations`:`/workspaces/${target}/invitations`;const result=await apiFetch<{token:string}>(path,{method:"POST",body:JSON.stringify({phone,role})});setMsg(`邀请已创建，请通过受控渠道发送令牌：${result.token}`);}catch(err){setMsg(err instanceof ApiError?err.message:"邀请创建失败");}}function changeScope(value:string){setScope(value);if(value==="company"){setTarget(companyOptions[0]?.id??"");setRole("COMPANY_MEMBER");}else{setTarget(workspaceOptions[0]?.id??"");setRole("RECRUITER");}}return <form onSubmit={submit} className="mt-4 rounded-xl border border-[#d6e5f5] bg-white p-5"><h2 className="m-0 flex items-center gap-2 text-base"><MailPlus size={17}/>邀请成员</h2><p className="mt-1 text-xs text-[#7187a8]">成员邀请不是平台注册门槛；令牌仅允许目标手机号接受。</p><div className="mt-4 grid gap-3 md:grid-cols-2 xl:grid-cols-5"><select value={scope} onChange={e=>changeScope(e.target.value)} className="h-10 rounded-lg border border-[#cbdbea] px-3 text-sm">{workspaceOptions.length>0&&<option value="workspace">Workspace</option>}{companyOptions.length>0&&<option value="company">企业</option>}</select><select value={target} onChange={e=>setTarget(e.target.value)} className="h-10 rounded-lg border border-[#cbdbea] px-3 text-sm">{(scope==="company"?companyOptions:workspaceOptions).map(item=><option key={item.id} value={item.id}>{"displayName" in item?item.displayName:item.name}</option>)}</select><input required value={phone} onChange={e=>setPhone(e.target.value)} placeholder="成员手机号" className="h-10 rounded-lg border border-[#cbdbea] px-3 text-sm"/><select value={role} onChange={e=>setRole(e.target.value)} className="h-10 rounded-lg border border-[#cbdbea] px-3 text-sm">{scope==="company"?<><option value="COMPANY_MEMBER">企业成员</option><option value="COMPANY_ADMIN">企业管理员</option></>:<><option value="RECRUITER">招聘成员</option><option value="WORKSPACE_ADMIN">空间管理员</option></>}</select><button disabled={!target} className="primary-button !h-10" type="submit">生成邀请</button></div>{msg&&<p className="mb-0 mt-3 break-all text-sm text-[#526f98]">{msg}</p>}</form>}
function Card({children}:{children:React.ReactNode}){return <article className="rounded-xl border border-[#d6e5f5] bg-white p-5 shadow-[0_6px_20px_rgba(30,92,160,0.04)]">{children}</article>}
