"use client";
/* eslint-disable react-hooks/set-state-in-effect, react-hooks/exhaustive-deps */

import { Building2, CheckCircle2, EyeOff, LogOut, MailPlus, Plus, Search, UserRound, UsersRound, X } from "lucide-react";
import { FormEvent, useState, useEffect } from "react";
import { AppShell } from "@/components/layout/app-shell";
import { apiFetch, ApiError } from "@/lib/api-client";

type Me={id:string;maskedPhone:string;personalVerificationStatus:string};
type Company={id:string;displayName:string;legalName:string;verificationStatus:string;role:string};
type Workspace={id:string;companyId:string|null;type:string;name:string;ownerUserId:string;status:string;memberCount:number;hasDataAccess:boolean;currentRole:string|null};
type CompanySearchResult={id:string;displayName:string;legalName:string;verificationStatus:string;memberCount:number};
type CompanyApplication={id:string;applicantPhone:string;evidence:string;status:string};

export default function SettingsPage(){
  const [me,setMe]=useState<Me|null>(null);const[companies,setCompanies]=useState<Company[]>([]);const[workspaces,setWorkspaces]=useState<Workspace[]>([]);const[message,setMessage]=useState("");const[companyModal,setCompanyModal]=useState<"join"|"create"|null>(null);
  async function load(){try{const[u,c,w]=await Promise.all([apiFetch<Me>("/me"),apiFetch<Company[]>("/companies"),apiFetch<Workspace[]>("/workspaces")]);setMe(u);setCompanies(c);setWorkspaces(w);}catch(e){setMessage(e instanceof ApiError?e.message:"加载失败");}}
  useEffect(()=>{let active=true;Promise.all([apiFetch<Me>("/me"),apiFetch<Company[]>("/companies"),apiFetch<Workspace[]>("/workspaces")]).then(([u,c,w])=>{if(active){setMe(u);setCompanies(c);setWorkspaces(w);}}).catch(e=>{if(active)setMessage(e instanceof ApiError?e.message:"加载失败");});return()=>{active=false};},[]);
  return <AppShell activeItem="设置"><section><h1 className="m-0 text-[25px] font-bold text-[#09245d]">组织与工作空间</h1><p className="mt-1 text-sm text-[#55709d]">企业角色只管理治理元数据，招聘数据始终按 Workspace 成员关系隔离。</p></section>
    {message&&<p className="mt-4 rounded-lg bg-red-50 p-3 text-sm text-red-700">{message}</p>}
    <div className="mt-5 grid gap-4 xl:grid-cols-[340px_minmax(0,1fr)]"><aside className="space-y-4"><Card><UserRound className="text-[#2f6bff]"/><h2 className="mb-1 mt-3 text-base">当前账号</h2><p className="m-0 text-sm text-[#667d9f]">{me?.maskedPhone??"加载中…"}</p><span className="mt-3 inline-block rounded-md bg-[#edf5ff] px-2 py-1 text-xs text-[#2467ca]">实名认证：{me?.personalVerificationStatus??"--"}</span>{me?.personalVerificationStatus==="UNVERIFIED"&&<PersonalVerify onDone={load}/>}<button type="button" onClick={async()=>{await apiFetch("/auth/logout-all",{method:"POST"});window.location.replace("/login");}} className="outline-button mt-4 w-full text-red-600"><LogOut size={15}/>退出全部设备</button></Card>
      <Card><Building2 className="text-[#16a477]"/><h2 className="mb-3 mt-3 text-base">所属企业</h2>{companies.length?companies.map(c=><div key={c.id} className="mb-2 rounded-lg border border-[#dce7f3] p-3"><strong className="text-sm">{c.displayName}</strong><small className="mt-1 block text-[#7187a8]">{c.role} · {c.verificationStatus}</small></div>):<><p className="text-sm text-[#7187a8]">尚未加入企业</p><div className="mt-4 grid gap-2 sm:grid-cols-2"><button type="button" onClick={()=>setCompanyModal("join")} className="outline-button !h-10"><Search size={15}/>加入企业</button><button type="button" onClick={()=>setCompanyModal("create")} className="primary-button !h-10"><Plus size={15}/>创建企业</button></div></>}</Card></aside>
      <section><div className="grid gap-3 md:grid-cols-2">{workspaces.map(w=><Card key={w.id}><div className="flex items-start justify-between"><span className="grid h-10 w-10 place-items-center rounded-xl bg-[#eaf7ff] text-[#2471dc]"><UsersRound size={20}/></span><span className={`rounded-md px-2 py-1 text-xs ${w.hasDataAccess?"bg-emerald-50 text-emerald-700":"bg-slate-100 text-slate-600"}`}>{w.hasDataAccess?"可访问业务数据":"仅治理元数据"}</span></div><h2 className="mb-1 mt-3 text-base">{w.name}</h2><p className="m-0 text-xs text-[#7187a8]">{w.type} · {w.memberCount} 名成员 · {w.status}</p>{!w.hasDataAccess&&<p className="mt-3 flex items-center gap-2 text-xs text-[#667d9f]"><EyeOff size={14}/>未加入该 Workspace，职位、人才、简历和任务不可见</p>}</Card>)}</div>
      {me&&companies.some(c=>["COMPANY_OWNER","COMPANY_ADMIN"].includes(c.role))&&<><CreateWorkspace companies={companies} ownerId={me.id} onDone={load}/><CompanyApplications companies={companies}/></>}<TeamInvitations key={`${companies.length}:${workspaces.length}`} companies={companies} workspaces={workspaces}/></section></div>
    {companyModal && (
      <CompanyModal mode={companyModal} onClose={() => setCompanyModal(null)} onDone={load}/>
    )}
  </AppShell>;
}

function CompanyModal({mode,onClose,onDone}:{mode:"join"|"create";onClose:()=>void;onDone:()=>Promise<void>}){
  return <div className="fixed inset-0 z-50 grid place-items-center bg-[#071b4b]/40 p-5 backdrop-blur-sm" role="presentation">
    <section className="max-h-[90vh] w-full max-w-xl overflow-y-auto rounded-2xl border border-white bg-white p-6 shadow-[0_24px_80px_rgba(7,27,75,.24)]" role="dialog" aria-modal="true" aria-labelledby="company-modal-title">
      <div className="flex items-start justify-between gap-4"><div><h2 id="company-modal-title" className="m-0 text-xl font-bold text-[#09245d]">{mode==="join"?"加入企业":"创建企业"}</h2><p className="mb-0 mt-1 text-sm text-[#7187a8]">{mode==="join"?"搜索已注册企业并提交加入申请，等待企业 Owner 或管理员审核":"填写企业信息，提交后由平台审核"}</p></div><button type="button" onClick={onClose} className="grid h-9 w-9 place-items-center rounded-full text-[#7187a8] hover:bg-[#f2f6fb]" aria-label="关闭"><X size={18}/></button></div>
      <div className="mt-6">{mode==="join"?<JoinCompanyForm onDone={onDone}/>:<CreateCompanyForm onDone={onDone}/>}</div>
    </section>
  </div>;
}

function JoinCompanyForm({onDone}:{onDone:()=>Promise<void>}){
  const [query,setQuery]=useState("");const[results,setResults]=useState<CompanySearchResult[]>([]);const[loading,setLoading]=useState(false);const[searched,setSearched]=useState(false);const[applyingId,setApplyingId]=useState<string|null>(null);const[message,setMessage]=useState("");const[error,setError]=useState(false);
  async function search(){if(!query.trim()){setResults([]);setSearched(false);return;}setLoading(true);setSearched(true);setMessage("");try{setResults(await apiFetch<CompanySearchResult[]>(`/companies/search?q=${encodeURIComponent(query.trim())}`));}catch(e){setResults([]);setMessage(e instanceof ApiError?e.message:"搜索失败，请稍后重试");setError(true);}finally{setLoading(false);}}
  async function apply(companyId:string){setApplyingId(companyId);setMessage("");setError(false);try{await apiFetch(`/companies/${companyId}/membership-applications`,{method:"POST",body:JSON.stringify({evidence:"通过组织与空间页面搜索申请加入"})});setMessage("加入申请已提交，请等待该企业 Owner 或管理员审核。");await onDone();}catch(e){setMessage(e instanceof ApiError?e.message:"申请失败，请稍后重试");setError(true);}finally{setApplyingId(null);}}
  return <form onSubmit={e=>{e.preventDefault();void search();}} className="space-y-4"><label className="block text-sm font-medium"><span className="mb-2 block">搜索企业名称</span><div className="flex gap-2"><div className="relative flex-1"><Search size={16} className="absolute left-3 top-1/2 -translate-y-1/2 text-[#9ab1d4]"/><input autoFocus value={query} onChange={e=>setQuery(e.target.value)} placeholder="输入企业名称或简称" className="h-11 w-full rounded-lg border border-[#cddbea] bg-white pl-9 pr-3 outline-none focus:border-[#2f6bff]"/></div><button className="primary-button !h-11 !px-5" type="submit" disabled={loading||!query.trim()}>{loading?"搜索中…":"搜索"}</button></div></label>{message&&<p className={`rounded-lg px-3 py-2 text-sm ${error?"bg-red-50 text-red-700":"bg-emerald-50 text-emerald-700"}`}>{message}</p>}{searched&&!loading&&!results.length&&!message&&<p className="text-sm text-[#7187a8]">未找到匹配的企业</p>}{results.length>0&&<div className="space-y-2">{results.map(company=><div key={company.id} className="flex items-center justify-between gap-3 rounded-lg border border-[#d8e6f5] bg-[#fbfdff] p-3"><div><p className="m-0 text-sm font-medium text-[#10285b]">{company.displayName}</p><p className="m-0 mt-1 text-xs text-[#7187a8]">{company.legalName} · {company.memberCount} 名成员</p></div><button type="button" onClick={()=>void apply(company.id)} disabled={applyingId!==null} className="outline-button !h-9 shrink-0 !px-3">{applyingId===company.id?"提交中…":"申请加入"}</button></div>)}</div>}</form>;
}

function CreateCompanyForm({onDone}:{onDone:()=>Promise<void>}){
  const [form,setForm]=useState({legalName:"",displayName:"",creditCode:"",licenseReference:"",firstWorkspaceName:"招聘团队"});const[msg,setMsg]=useState("");const[error,setError]=useState(false);const[loading,setLoading]=useState(false);
  function change(key:keyof typeof form,value:string){setForm(previous=>({...previous,[key]:value}));}
  async function submit(e:FormEvent){e.preventDefault();setLoading(true);setMsg("");setError(false);try{const result=await apiFetch<{id:string}>("/company-verifications",{method:"POST",body:JSON.stringify(form)});setMsg(`企业创建申请已提交（申请号 ${result.id.slice(0,8)}），平台审核通过后创建企业和首个工作空间。`);await onDone();}catch(err){setMsg(err instanceof ApiError?err.message:"提交失败，请稍后重试");setError(true);}finally{setLoading(false);}}
  return <form onSubmit={submit} className="space-y-4"><div className="grid gap-4 sm:grid-cols-2"><CompanyField label="企业法定名称" value={form.legalName} onChange={value=>change("legalName",value)}/><CompanyField label="企业简称" value={form.displayName} onChange={value=>change("displayName",value)}/><CompanyField label="统一社会信用代码" value={form.creditCode} onChange={value=>change("creditCode",value)}/><CompanyField label="首个 Workspace 名称" value={form.firstWorkspaceName} onChange={value=>change("firstWorkspaceName",value)}/></div><CompanyField label="营业执照材料引用" value={form.licenseReference} onChange={value=>change("licenseReference",value)} placeholder="文件编号或受控存储引用"/>{msg&&<p className={`rounded-lg px-3 py-2 text-sm ${error?"bg-red-50 text-red-700":"bg-emerald-50 text-emerald-700"}`}><CheckCircle2 className="mr-2 inline-block" size={16}/>{msg}</p>}<button className="primary-button w-full" disabled={loading} type="submit">{loading?"提交中…":"提交平台审核"}</button></form>;
}

function CompanyField({label,value,onChange,placeholder}:{label:string;value:string;onChange:(value:string)=>void;placeholder?:string}){return <label className="block text-sm font-medium"><span className="mb-2 block">{label}</span><input required value={value} onChange={e=>onChange(e.target.value)} placeholder={placeholder} className="h-11 w-full rounded-lg border border-[#cddbea] bg-white px-3 outline-none focus:border-[#2f6bff]"/></label>;}

function CreateWorkspace({companies,ownerId,onDone}:{companies:Company[];ownerId:string;onDone:()=>Promise<void>}){const[companyId,setCompanyId]=useState(companies[0]?.id??"");const[name,setName]=useState("");const[msg,setMsg]=useState("");async function submit(e:FormEvent){e.preventDefault();try{await apiFetch(`/companies/${companyId}/workspaces`,{method:"POST",body:JSON.stringify({name,ownerUserId:ownerId})});setName("");setMsg("Workspace 已创建，你被指定为 Workspace Owner。");await onDone();}catch(err){setMsg(err instanceof ApiError?err.message:"创建失败");}}return <form onSubmit={submit} className="mt-4 rounded-xl border border-[#d6e5f5] bg-white p-5"><h2 className="m-0 flex items-center gap-2 text-base"><Plus size={17}/>创建企业 Workspace</h2><p className="mt-1 text-xs text-[#7187a8]">仅 Company Owner/Admin 可创建；创建者只有成为空间成员后才拥有业务数据权限。</p><div className="mt-4 grid gap-3 sm:grid-cols-[220px_1fr_auto]"><select value={companyId} onChange={e=>setCompanyId(e.target.value)} className="h-10 rounded-lg border border-[#cbdbea] px-3 text-sm">{companies.filter(c=>["COMPANY_OWNER","COMPANY_ADMIN"].includes(c.role)).map(c=><option key={c.id} value={c.id}>{c.displayName}</option>)}</select><input required value={name} onChange={e=>setName(e.target.value)} placeholder="Workspace 名称" className="h-10 rounded-lg border border-[#cbdbea] px-3 text-sm"/><button className="primary-button !h-10" type="submit">创建</button></div>{msg&&<p className="mb-0 mt-3 text-sm text-[#526f98]">{msg}</p>}</form>}
function CompanyApplications({companies}:{companies:Company[]}){const[companyId,setCompanyId]=useState(companies.find(c=>["COMPANY_OWNER","COMPANY_ADMIN"].includes(c.role))?.id??"");const[items,setItems]=useState<CompanyApplication[]>([]);const[msg,setMsg]=useState("");async function load(){if(companyId)setItems(await apiFetch<CompanyApplication[]>(`/companies/${companyId}/membership-applications`));}useEffect(()=>{void load();},[companyId]);async function review(id:string,action:"approve"|"reject"){try{await apiFetch(`/companies/${companyId}/membership-applications/${id}/${action}`,{method:"POST",body:action==="reject"?JSON.stringify({reason:"不符合企业成员要求"}):undefined});setMsg(action==="approve"?"已批准加入申请":"已拒绝加入申请");await load();}catch(e){setMsg(e instanceof ApiError?e.message:"操作失败");}}return <Card><div className="flex items-center justify-between gap-3"><h2 className="m-0 text-base">加入企业申请</h2><select value={companyId} onChange={e=>setCompanyId(e.target.value)} className="h-9 rounded-lg border border-[#cbdbea] px-2 text-sm">{companies.filter(c=>["COMPANY_OWNER","COMPANY_ADMIN"].includes(c.role)).map(c=><option key={c.id} value={c.id}>{c.displayName}</option>)}</select></div>{msg&&<p className="text-sm text-[#526f98]">{msg}</p>}{!items.length?<p className="text-sm text-[#7187a8]">暂无加入申请</p>:<div className="mt-3 space-y-2">{items.filter(i=>i.status==="PENDING").map(i=><div key={i.id} className="flex items-center justify-between rounded-lg border border-[#dce7f3] p-3"><span className="text-sm">手机号尾号 {i.applicantPhone} · {i.evidence}</span><span className="flex gap-2"><button type="button" onClick={()=>void review(i.id,"approve")} className="primary-button !h-8 !px-3">批准</button><button type="button" onClick={()=>void review(i.id,"reject")} className="outline-button !h-8 !px-3">拒绝</button></span></div>)}</div>}</Card>}
function PersonalVerify({onDone}:{onDone:()=>Promise<void>}){const[name,setName]=useState("");const[number,setNumber]=useState("");const[msg,setMsg]=useState("");async function submit(e:FormEvent){e.preventDefault();try{await apiFetch("/personal-verifications",{method:"POST",body:JSON.stringify({realName:name,identityNumber:number})});setMsg("认证已提交，平台审核通过后发放30元试用金。");await onDone();}catch(err){setMsg(err instanceof ApiError?err.message:"提交失败");}}return <form onSubmit={submit} className="mt-4 space-y-2 border-t border-[#e0eaf5] pt-4"><input required value={name} onChange={e=>setName(e.target.value)} placeholder="真实姓名" className="h-9 w-full rounded-lg border border-[#cbdbea] px-3 text-sm"/><input required value={number} onChange={e=>setNumber(e.target.value)} placeholder="身份证明号码" className="h-9 w-full rounded-lg border border-[#cbdbea] px-3 text-sm"/><button className="outline-button !h-9 w-full" type="submit">提交实名认证</button>{msg&&<p className="text-xs text-[#526f98]">{msg}</p>}</form>}
function TeamInvitations({companies,workspaces}:{companies:Company[];workspaces:Workspace[]}){const companyOptions=companies.filter(c=>["COMPANY_OWNER","COMPANY_ADMIN"].includes(c.role));const workspaceOptions=workspaces.filter(w=>["WORKSPACE_OWNER","WORKSPACE_ADMIN"].includes(w.currentRole??""));const[scope,setScope]=useState(workspaceOptions.length?"workspace":"company");const[target,setTarget]=useState(workspaceOptions[0]?.id??companyOptions[0]?.id??"");const[phone,setPhone]=useState("");const[role,setRole]=useState(workspaceOptions.length?"RECRUITER":"COMPANY_MEMBER");const[msg,setMsg]=useState("");if(!companyOptions.length&&!workspaceOptions.length)return null;async function submit(e:FormEvent){e.preventDefault();try{const path=scope==="company"?`/companies/${target}/invitations`:`/workspaces/${target}/invitations`;const result=await apiFetch<{token:string}>(path,{method:"POST",body:JSON.stringify({phone,role})});setMsg(`邀请已创建，请通过受控渠道发送令牌：${result.token}`);}catch(err){setMsg(err instanceof ApiError?err.message:"邀请创建失败");}}function changeScope(value:string){setScope(value);if(value==="company"){setTarget(companyOptions[0]?.id??"");setRole("COMPANY_MEMBER");}else{setTarget(workspaceOptions[0]?.id??"");setRole("RECRUITER");}}return <form onSubmit={submit} className="mt-4 rounded-xl border border-[#d6e5f5] bg-white p-5"><h2 className="m-0 flex items-center gap-2 text-base"><MailPlus size={17}/>邀请成员</h2><p className="mt-1 text-xs text-[#7187a8]">成员邀请不是平台注册门槛；令牌仅允许目标手机号接受。</p><div className="mt-4 grid gap-3 md:grid-cols-2 xl:grid-cols-5"><select value={scope} onChange={e=>changeScope(e.target.value)} className="h-10 rounded-lg border border-[#cbdbea] px-3 text-sm">{workspaceOptions.length>0&&<option value="workspace">Workspace</option>}{companyOptions.length>0&&<option value="company">企业</option>}</select><select value={target} onChange={e=>setTarget(e.target.value)} className="h-10 rounded-lg border border-[#cbdbea] px-3 text-sm">{(scope==="company"?companyOptions:workspaceOptions).map(item=><option key={item.id} value={item.id}>{"displayName" in item?item.displayName:item.name}</option>)}</select><input required value={phone} onChange={e=>setPhone(e.target.value)} placeholder="成员手机号" className="h-10 rounded-lg border border-[#cbdbea] px-3 text-sm"/><select value={role} onChange={e=>setRole(e.target.value)} className="h-10 rounded-lg border border-[#cbdbea] px-3 text-sm">{scope==="company"?<><option value="COMPANY_MEMBER">企业成员</option><option value="COMPANY_ADMIN">企业管理员</option></>:<><option value="RECRUITER">招聘成员</option><option value="WORKSPACE_ADMIN">空间管理员</option></>}</select><button disabled={!target} className="primary-button !h-10" type="submit">生成邀请</button></div>{msg&&<p className="mb-0 mt-3 break-all text-sm text-[#526f98]">{msg}</p>}</form>}
function Card({children}:{children:React.ReactNode}){return <article className="rounded-xl border border-[#d6e5f5] bg-white p-5 shadow-[0_6px_20px_rgba(30,92,160,0.04)]">{children}</article>}
