"use client";

import { Building2, CheckCircle2, LogOut, Search, UserRound } from "lucide-react";
import Link from "next/link";
import { FormEvent, useCallback, useEffect, useRef, useState } from "react";
import { useRouter } from "next/navigation";
import { ApiError, apiFetch, setAccessToken } from "@/lib/api-client";
import { useWorkspace } from "@/lib/workspace-context";

type Mode = "personal" | "company";
type CompanyMode = "create" | "join";
type PendingRegistration = { legalName: string; status: string };
type Company = { companyId: string; legalName: string; memberCount: number };

/** BOSS creates Personal Tenant automatically. A legal Company is created only by enterprise registration. */
export default function OnboardingPage() {
  const [mode, setMode] = useState<Mode>("personal");
  const [pending, setPending] = useState<PendingRegistration | null>(null);
  const router = useRouter();
  const { refresh } = useWorkspace();
  const loadPending = useCallback(async () => {
    try { const items = await apiFetch<PendingRegistration[]>("/companies/registrations/pending"); setPending(items[0] ?? null); }
    catch (error) { if (error instanceof ApiError && error.status === 401) router.replace("/login"); }
  }, [router]);
  useEffect(() => { void loadPending(); }, [loadPending]);
  async function usePersonal() { await refresh(); router.replace("/recruitment"); }
  async function logout() { try { await apiFetch("/auth/logout", { method: "POST" }); } finally { setAccessToken(null); router.replace("/login"); } }

  if (pending) return <main className="min-h-screen bg-[#f7fbff] text-[#10285b]"><header className="app-header flex h-[66px] items-center justify-between border-b border-[#dbe9f8] px-6 lg:px-8"><div className="flex items-center gap-3 text-[21px] font-bold tracking-tight text-[#09245d]"><span className="brand-mark" aria-hidden="true"><i/><i/></span>AI招聘工作台</div><button type="button" aria-label="退出当前设备" onClick={() => void logout()} className="grid h-9 w-9 place-items-center rounded-full text-[#405781] hover:bg-white/70"><LogOut size={17}/></button></header><div className="grid min-h-[calc(100vh-66px)] place-items-center p-5"><div className="w-full max-w-xl rounded-2xl bg-white p-10 text-center shadow-xl"><Building2 className="mx-auto text-[#2f6bff]" size={42}/><h1 className="mt-5 text-2xl font-bold">企业申请审核中</h1><p className="mt-4 text-[#60799f]">您提交的“{pending.legalName}”企业信息正在由平台审核，审核结果以 BOSS 状态为准。</p></div></div></main>;

  return <main className="login-canvas min-h-screen p-5 text-[#10285b] lg:p-10"><div className="mx-auto max-w-5xl rounded-[26px] border border-white/80 bg-white/95 p-7 shadow-[0_18px_60px_rgba(39,100,180,0.09)] sm:p-10"><div className="flex items-center gap-3 text-xl font-bold text-[#09245d]"><span className="brand-mark" aria-hidden="true"><i/><i/></span>AI招聘工作台</div><h1 className="mb-0 mt-8 text-3xl font-bold">选择使用方式</h1><p className="mt-2 text-sm text-[#60799f]">个人账号可随时加入或创建认证企业。</p><Link href="/login" className="mt-3 inline-block text-sm text-[#176ce5] hover:underline">返回登录页</Link><div className="mt-7 grid gap-3 md:grid-cols-2"><ModeButton active={mode === "personal"} onClick={() => setMode("personal")} icon={<UserRound/>} title="个人使用" desc="个人 HR 或 SOHO 猎头"/><ModeButton active={mode === "company"} onClick={() => setMode("company")} icon={<Building2/>} title="认证企业" desc="创建企业或加入已有企业"/></div><section className="mt-6 rounded-2xl border border-[#d8e6f5] bg-[#f9fcff] p-6">{mode === "personal" ? <PersonalPanel onEnter={() => void usePersonal()}/> : <CompanyPanel onSubmitted={() => void loadPending()}/>}</section></div></main>;
}

function ModeButton({ active, onClick, icon, title, desc }: { active: boolean; onClick: () => void; icon: React.ReactNode; title: string; desc: string }) { return <button type="button" onClick={onClick} className={`rounded-2xl border p-5 text-left transition ${active ? "border-[#2f6bff] bg-[#edf5ff] shadow-[0_0_0_3px_rgba(47,107,255,.08)]" : "border-[#d8e4f1] bg-white hover:border-[#a9c6ea]"}`}><span className="text-[#2671ed]">{icon}</span><strong className="mt-3 block">{title}</strong><small className="mt-1 block text-[#7187a8]">{desc}</small></button>; }
function PersonalPanel({ onEnter }: { onEnter: () => void }) { return <div><Heading title="使用个人账号" note="BOSS 已为当前账号创建 Personal Tenant。个人使用不创建 Company，招聘数据由个人主体隔离。"/><button type="button" onClick={onEnter} className="primary-button mt-5">进入个人招聘工作台</button></div>; }
function CompanyPanel({ onSubmitted }: { onSubmitted: () => void }) { const [subMode, setSubMode] = useState<CompanyMode>("create"); return <div><div className="mb-5 flex gap-3"><SubMode active={subMode === "create"} onClick={() => setSubMode("create")} title="创建企业" desc="提交企业认证，审核通过后启用 Company"/><SubMode active={subMode === "join"} onClick={() => setSubMode("join")} title="加入企业" desc="搜索已认证企业并申请加入"/></div>{subMode === "create" ? <EnterpriseForm onSubmitted={onSubmitted}/> : <JoinCompanyForm/>}</div>; }
function SubMode({ active, onClick, title, desc }: { active: boolean; onClick: () => void; title: string; desc: string }) { return <button type="button" onClick={onClick} className={`flex-1 rounded-xl border p-4 text-left transition ${active ? "border-[#2f6bff] bg-[#edf5ff] shadow-[0_0_0_3px_rgba(47,107,255,.08)]" : "border-[#d8e4f1] bg-white hover:border-[#a9c6ea]"}`}><strong className="block text-sm">{title}</strong><small className="mt-1 block text-xs text-[#7187a8]">{desc}</small></button>; }
function EnterpriseForm({ onSubmitted }: { onSubmitted: () => void }) { const [form, setForm] = useState({ legalName: "", creditCode: "", licenseReference: "", contactName: "", contactPhone: "" }); const [fileName, setFileName] = useState(""); const [uploading, setUploading] = useState(false); const [loading, setLoading] = useState(false); const [message, setMessage] = useState(""); function set(key: keyof typeof form, value: string) { setForm(current => ({ ...current, [key]: value })); } async function upload(file: File | undefined) { if (!file) return; setUploading(true); setMessage(""); try { const body = new FormData(); body.append("file", file); const result = await apiFetch<{ reference: string; filename: string }>("/companies/registrations/license-files", { method: "POST", body }); set("licenseReference", result.reference); setFileName(result.filename); } catch (error) { set("licenseReference", ""); setFileName(""); setMessage(error instanceof ApiError ? error.message : "营业执照上传失败，请稍后重试"); } finally { setUploading(false); } } async function submit(event: FormEvent) { event.preventDefault(); setLoading(true); setMessage(""); try { await apiFetch("/companies/registrations", { method: "POST", body: JSON.stringify(form) }); onSubmitted(); } catch (error) { setMessage(error instanceof ApiError ? error.message : "提交失败，请稍后重试"); } finally { setLoading(false); } } return <form onSubmit={submit} className="space-y-4"><Heading title="企业认证" note="企业、营业执照、审核和审计记录均由 BOSS 管理。"/><div className="grid gap-4 sm:grid-cols-2"><Field label="企业法定名称" value={form.legalName} onChange={value => set("legalName", value)}/><Field label="统一社会信用代码" value={form.creditCode} onChange={value => set("creditCode", value)}/><Field label="联系人" value={form.contactName} onChange={value => set("contactName", value)}/><Field label="联系人手机号" value={form.contactPhone} onChange={value => set("contactPhone", value)}/></div><label className="block text-sm font-medium"><span className="mb-2 block">营业执照</span><input required disabled={uploading} type="file" accept="image/jpeg,image/png,image/webp,application/pdf,.jpg,.jpeg,.png,.webp,.pdf" onChange={event => void upload(event.target.files?.[0])} className="block w-full rounded-lg border border-[#cddbea] bg-white p-2 text-sm"/><small className="mt-1 block text-xs text-[#7187a8]">支持 JPG、PNG、WEBP、PDF，最大 10MB{fileName && ` · 已上传：${fileName}`}</small></label>{message && <Notice message={message}/>}<button className="primary-button" disabled={loading || uploading || !form.licenseReference} type="submit">{loading ? "提交中…" : uploading ? "营业执照上传中…" : "提交 BOSS 审核"}</button></form>; }
function JoinCompanyForm() { const [query, setQuery] = useState(""); const [results, setResults] = useState<Company[]>([]); const [loading, setLoading] = useState(false); const [message, setMessage] = useState(""); const timer = useRef<ReturnType<typeof setTimeout> | null>(null); const search = useCallback(async (value: string) => { if (value.trim().length < 2) { setResults([]); return; } setLoading(true); try { setResults(await apiFetch<Company[]>(`/companies/search?q=${encodeURIComponent(value.trim())}`)); } catch (error) { setMessage(error instanceof ApiError ? error.message : "搜索失败"); } finally { setLoading(false); } }, []); useEffect(() => { if (timer.current) clearTimeout(timer.current); timer.current = setTimeout(() => void search(query), 300); return () => { if (timer.current) clearTimeout(timer.current); }; }, [query, search]); async function apply(companyId: string) { try { await apiFetch(`/companies/${companyId}/membership-applications`, { method: "POST" }); setMessage("加入申请已提交，请等待企业 Owner 或管理员审核。"); } catch (error) { setMessage(error instanceof ApiError ? error.message : "申请失败"); } } return <div className="space-y-4"><Heading title="加入已有企业" note="搜索已通过审核的企业并申请加入。"/><label className="block text-sm font-medium"><span className="mb-2 block">搜索企业名称</span><div className="relative"><Search size={16} className="absolute left-3 top-1/2 -translate-y-1/2 text-[#9ab1d4]"/><input value={query} onChange={event => setQuery(event.target.value)} placeholder="输入企业名称" className="h-11 w-full rounded-lg border border-[#cddbea] bg-white pl-9 pr-3 outline-none focus:border-[#2f6bff]"/></div></label>{loading && <p className="text-sm text-[#7187a8]">搜索中…</p>}{message && <Notice message={message}/>}<div className="space-y-2">{results.map(item => <div key={item.companyId} className="flex items-center justify-between rounded-lg border border-[#d8e6f5] bg-white p-3"><div><p className="m-0 text-sm font-medium">{item.legalName}</p><p className="m-0 mt-1 text-xs text-[#7187a8]">{item.memberCount} 名成员</p></div><button type="button" onClick={() => void apply(item.companyId)} className="outline-button !h-9 !px-3">申请加入</button></div>)}</div></div>; }
function Heading({ title, note }: { title: string; note: string }) { return <div><h2 className="m-0 text-lg font-bold">{title}</h2><p className="mb-0 mt-1 text-sm text-[#6b82a6]">{note}</p></div>; }
function Field({ label, value, onChange }: { label: string; value: string; onChange: (value: string) => void }) { return <label className="block text-sm font-medium"><span className="mb-2 block">{label}</span><input required value={value} onChange={event => onChange(event.target.value)} className="h-11 w-full rounded-lg border border-[#cddbea] bg-white px-3 outline-none focus:border-[#2f6bff]"/></label>; }
function Notice({ message }: { message: string }) { return <p className="flex items-start gap-2 rounded-lg bg-emerald-50 px-3 py-2 text-sm text-emerald-700"><CheckCircle2 className="mt-0.5 shrink-0" size={16}/>{message}</p>; }
