"use client";

import { Building2, CheckCircle2, Search } from "lucide-react";
import { FormEvent, useEffect, useRef, useState } from "react";
import { apiFetch, ApiError } from "@/lib/api-client";
import { AppShell } from "@/components/layout/app-shell";

type Enterprise = { tenantId: string; tenantName: string; legalName: string };

export default function OnboardingPage() {
  const [tab, setTab] = useState<"create" | "join">("create");
  return <AppShell activeItem="" pageHeader={<section><h1 className="m-0 text-[25px] font-bold text-[#09245d]">注册或申请加入企业</h1><p className="mb-0 mt-1 text-sm text-[#60799f]">提交企业注册申请，或搜索并申请加入已有企业。</p></section>}><div className="mx-auto flex min-h-[480px] max-w-3xl flex-col rounded-xl border border-[#d6e5f5] bg-white p-8 shadow-[0_6px_20px_rgba(30,92,160,0.04)]">
    <div className="grid gap-3 md:grid-cols-2"><Tab active={tab === "create"} onClick={() => setTab("create")} icon={<Building2/>} title="注册企业"/><Tab active={tab === "join"} onClick={() => setTab("join")} icon={<Search/>} title="加入企业"/></div>
    <section className="mt-6 flex-1 rounded-2xl border border-[#d8e6f5] bg-[#f9fcff] p-6">
      {tab === "create" && <EnterpriseRegistration/>} {tab === "join" && <JoinEnterprise/>}
    </section>
  </div></AppShell>;
}

function Tab({ active, onClick, icon, title }: { active: boolean; onClick: () => void; icon: React.ReactNode; title: string }) { return <button type="button" onClick={onClick} className={`rounded-xl border p-4 text-left transition ${active ? "border-[#2f6bff] bg-[#edf5ff]" : "border-[#d8e4f1] bg-white hover:border-[#a9c6ea]"}`}><span className="text-[#2671ed]">{icon}</span><strong className="mt-2 block text-sm">{title}</strong></button>; }

function EnterpriseRegistration() {
  const [legalName, setLegalName] = useState(""); const [creditCode, setCreditCode] = useState(""); const [contactName, setContactName] = useState(""); const [contactPhone, setContactPhone] = useState("");
  const [documentId, setDocumentId] = useState(""); const [fileName, setFileName] = useState(""); const [message, setMessage] = useState<string | null>(null); const [error, setError] = useState<string | null>(null); const [busy, setBusy] = useState(false);
  const fileInputRef = useRef<HTMLInputElement>(null);
  async function upload(file?: File) { if (!file) return; setBusy(true); setError(null); try { const form = new FormData(); form.append("file", file); const result = await apiFetch<{ document_id: string }>("/tenants/enterprise-registration-documents", { method: "POST", body: form }); setDocumentId(result.document_id); setFileName(file.name); } catch (cause) { setDocumentId(""); setFileName(""); setError(cause instanceof ApiError ? cause.message : "营业执照上传失败"); } finally { setBusy(false); } }
  async function submit(event: FormEvent) { event.preventDefault(); setBusy(true); setError(null); try { const availability = await apiFetch<{ available: boolean }>(`/tenants/enterprise-registration/credit-code-availability?creditCode=${encodeURIComponent(creditCode.trim().toUpperCase())}`); if (!availability.available) { setError("该统一社会信用代码已绑定有效企业租户，不能重复提交。"); return; } await apiFetch("/tenants/enterprise-registrations", { method: "POST", body: JSON.stringify({ legalName: legalName.trim(), creditCode: creditCode.trim().toUpperCase(), licenseDocumentId: documentId, contactName: contactName.trim(), contactPhone: contactPhone.trim() }) }); setMessage("企业注册申请已提交，审核通过后将按平台配置开通 Trial 或合同套餐。"); } catch (cause) { setError(cause instanceof ApiError ? cause.message : "提交企业注册失败"); } finally { setBusy(false); } }
  return <form onSubmit={submit} className="space-y-4"><h2 className="m-0 text-lg font-bold">注册企业</h2><p className="m-0 text-sm text-[#60799f]">提交企业法定名称、统一社会信用代码和营业执照原件照片，由平台运营审核。</p><Fields values={{ legalName, creditCode, contactName, contactPhone }} set={{ setLegalName, setCreditCode, setContactName, setContactPhone }}/><label className="block text-sm font-medium">营业执照原件照片<div className="mt-2 flex min-w-0 items-center gap-2"><input ref={fileInputRef} required type="file" accept="image/*" disabled={busy} onChange={event => void upload(event.target.files?.[0])} className="hidden"/><button type="button" className="outline-button shrink-0" disabled={busy} onClick={() => fileInputRef.current?.click()}>{documentId ? "重新上传" : "选择文件"}</button>{fileName && <span className="min-w-0 truncate text-sm text-[#7187a8]">{fileName}</span>}{documentId && <small className="shrink-0 text-emerald-700">已上传</small>}</div></label>{error && <Notice error>{error}</Notice>}{message && <Notice>{message}</Notice>}<button className="primary-button" disabled={busy || !documentId} type="submit">{busy ? "处理中…" : "提交审核"}</button></form>;
}

function Fields({ values, set }: { values: { legalName: string; creditCode: string; contactName: string; contactPhone: string }; set: Record<string, (value: string) => void> }) { const fields = [["企业法定名称", "legalName", "setLegalName"], ["统一社会信用代码", "creditCode", "setCreditCode"], ["联系人", "contactName", "setContactName"], ["联系电话", "contactPhone", "setContactPhone"]] as const; return <div className="grid gap-4 sm:grid-cols-2">{fields.map(([label, key, setter]) => <label key={key} className="block text-sm font-medium">{label}<input required value={values[key]} onChange={event => set[setter](event.target.value)} className="mt-2 h-10 w-full rounded-lg border border-[#cddbea] bg-white px-3 outline-none focus:border-[#2f6bff]"/></label>)}</div>; }

function JoinEnterprise() {
  const [keyword, setKeyword] = useState(""); const [items, setItems] = useState<Enterprise[]>([]); const [message, setMessage] = useState<string | null>(null); const [busy, setBusy] = useState<string | null>(null); const [searching, setSearching] = useState(false); const timer = useRef<ReturnType<typeof setTimeout> | null>(null);
  useEffect(() => { if (timer.current) clearTimeout(timer.current); if (!keyword.trim()) { setItems([]); setSearching(false); return; } setSearching(true); timer.current = setTimeout(() => { void apiFetch<Enterprise[]>(`/tenants/enterprises/search?keyword=${encodeURIComponent(keyword.trim())}`).then(setItems).catch(() => setItems([])).finally(() => setSearching(false)); }, 300); return () => { if (timer.current) clearTimeout(timer.current); }; }, [keyword]);
  async function apply(id: string) { setBusy(id); try { await apiFetch(`/tenants/${id}/join-applications`, { method: "POST", body: JSON.stringify({ roleCode: "MEMBER" }) }); setMessage("申请已提交；企业 Owner 审批且有空闲席位时，系统才会加入企业并自动占用席位。"); } catch (cause) { setMessage(cause instanceof ApiError ? cause.message : "申请加入失败"); } finally { setBusy(null); } }
  return <div className="space-y-4"><h2 className="m-0 text-lg font-bold">申请加入企业</h2><p className="m-0 text-sm text-[#60799f]">企业只管理本企业成员；您的其他企业归属不会被展示。</p><input value={keyword} onChange={event => setKeyword(event.target.value)} placeholder="输入企业名称" className="h-10 w-full rounded-lg border border-[#cddbea] bg-white px-3 outline-none focus:border-[#2f6bff]"/>{items.map(item => <div key={item.tenantId} className="flex items-center justify-between rounded-lg border border-[#d8e6f5] bg-white p-3"><div><strong className="block text-sm">{item.tenantName}</strong><small className="text-[#7187a8]">{item.legalName}</small></div><button type="button" className="outline-button text-xs" disabled={busy === item.tenantId} onClick={() => void apply(item.tenantId)}>{busy === item.tenantId ? "提交中…" : "申请加入"}</button></div>)}{!searching && keyword.trim() !== "" && items.length === 0 && <p className="py-4 text-center text-sm text-[#7187a8]">未查询到该企业</p>}{message && <Notice>{message}</Notice>}</div>;
}
function Notice({ children, error = false }: { children: React.ReactNode; error?: boolean }) { return <p className={`flex gap-2 rounded-lg px-3 py-2 text-sm ${error ? "bg-red-50 text-red-700" : "bg-emerald-50 text-emerald-700"}`}><CheckCircle2 size={16} className="mt-0.5 shrink-0"/>{children}</p>; }
