"use client";

import { Landmark, Save } from "lucide-react";
import { useEffect, useState, type FormEvent } from "react";
import { adminApiFetch } from "@/lib/admin-api-client";

type ReceivingAccount = { id: string; bankName: string; beneficiaryName: string; accountNumber: string; contactPhone?: string | null; contactEmail?: string | null };
const initial = { bankName: "", beneficiaryName: "", accountNumber: "", contactPhone: "", contactEmail: "" };

export default function RechargeSettingsPage() {
  const [form, setForm] = useState(initial); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [message, setMessage] = useState(""); const [error, setError] = useState("");
  useEffect(() => { adminApiFetch<ReceivingAccount | null>("/platform/recharge-settings").then((item) => { if (item) setForm({ bankName: item.bankName, beneficiaryName: item.beneficiaryName, accountNumber: item.accountNumber, contactPhone: item.contactPhone ?? "", contactEmail: item.contactEmail ?? "" }); }).catch((cause) => setError(cause instanceof Error ? cause.message : "收款账户加载失败")).finally(() => setLoading(false)); }, []);
  function change(key: keyof typeof form, value: string) { setForm((current) => ({ ...current, [key]: value })); }
  async function save(event: FormEvent) { event.preventDefault(); setSaving(true); setMessage(""); setError(""); try { await adminApiFetch<ReceivingAccount>("/platform/recharge-settings", { method: "PUT", body: JSON.stringify(form) }); setMessage("收款账户已保存，用户端会展示最新信息。"); } catch (cause) { setError(cause instanceof Error ? cause.message : "保存失败"); } finally { setSaving(false); } }
  return <div className="max-w-3xl"><div className="mb-6"><h1 className="flex items-center gap-2 text-2xl font-bold text-slate-800"><Landmark className="text-brand"/>收款账户配置</h1><p className="mt-1 text-sm text-slate-500">配置用户“对公付款”页面展示的收款账户。保存后会立即替换当前生效账户。</p></div>{loading ? <div className="rounded-xl border border-slate-200 bg-white p-6 text-sm text-slate-400">加载中…</div> : <form onSubmit={save} className="space-y-5 rounded-xl border border-slate-200 bg-white p-6 shadow-sm"><Field label="开户银行" value={form.bankName} onChange={(value) => change("bankName", value)} required/><Field label="收款户名" value={form.beneficiaryName} onChange={(value) => change("beneficiaryName", value)} required/><Field label="收款账号" value={form.accountNumber} onChange={(value) => change("accountNumber", value)} required/><div className="grid gap-5 sm:grid-cols-2"><Field label="联系手机（可选）" value={form.contactPhone} onChange={(value) => change("contactPhone", value)}/><Field label="联系邮箱（可选）" type="email" value={form.contactEmail} onChange={(value) => change("contactEmail", value)}/></div>{error && <p className="rounded-lg bg-red-50 px-4 py-3 text-sm text-red-700">{error}</p>}{message && <p className="rounded-lg bg-green-50 px-4 py-3 text-sm text-green-700">{message}</p>}<button disabled={saving} className="inline-flex h-10 items-center gap-2 rounded-lg bg-brand px-4 text-sm font-semibold text-white disabled:opacity-60"><Save size={16}/>{saving ? "保存中…" : "保存收款账户"}</button></form>}</div>;
}
function Field({ label, value, onChange, required, type = "text" }: { label: string; value: string; onChange: (value: string) => void; required?: boolean; type?: string }) { return <label className="block text-sm font-medium text-slate-700">{label}<input type={type} required={required} value={value} onChange={(event) => onChange(event.target.value)} className="mt-2 h-10 w-full rounded-lg border border-slate-300 px-3 text-sm outline-none focus:border-brand focus:ring-2 focus:ring-brand/10"/></label>; }
